spring:
  datasource: 
    url: jdbc:mysql://localhost:3306/cinyema?allowPublicKeyRetrieval=true&useSSL=false&useTimezone=true&serverTimezone=GMT&characterEncoding=UTF-8&createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
  thymeleaf:    prefix: classpath:/plantillas/
  mail:    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            required: true
            enable: true
    username: cinyema2021@gmail.com
    password: +cinyema2021+